# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb80f25b083f3407c8612151a7f55c30d7e811def1cbd884915304e6d2d81b874b7a2c3694c8e1891fb3f7b318020e5c506e5995640cafd25ac9c40266767267

test:
  secret_key_base: 769c88605be0886e5128e5b3e44a386919908986e18927271cd9036eae259aba45459ebb526c8c41ea5f0aae975610f00f7d5318e3e23b51e5b1b18760087d6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
